version: '3.8'

services:

  zookeeper:
    image: 'bitnami/zookeeper:3.8'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - feature_text_malicious_default

  kafka:
    image: 'bitnami/kafka:3.7'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - feature_text_malicious_default


  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
    depends_on:
      - kafka
    networks:
      - feature_text_malicious_default


  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  data_retrieval:
    build:
      context: DataRetrieval
      dockerfile: Dockerfile
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGO_USER=IRGC_NEW
      - MONGO_PASS=iran135
      - DBname=IranMalDB
      - collectionName=tweets
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    networks:
      - feature_text_malicious_default


  enricher:
    build:
      context: Enricher
      dockerfile: Dockerfile
    environment:
      - KAFKA_BROKER=kafka:9092
    ports:
      - "8001:8001"
    depends_on:
      - kafka
    networks:
      - feature_text_malicious_default


  persister:
    build:
      context: Persister
      dockerfile: Dockerfile
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=processed_tweets
    ports:
      - "8002:8002"
    depends_on:
      - kafka
      - mongodb
    networks:
      - feature_text_malicious_default






volumes:
  mongo_data:

networks:
  feature_text_malicious_default:
    driver: bridge
