apiVersion: v1
kind: Secret
metadata:
  name: fetch-tweets-secret
type: Opaque
data:
  MONGO-USER : SVJHQ19ORVc=
  MONGO-PASS : aXJhbjEzNQ==
  DBname : SXJhbk1hbERC
  collectionName : dHdlZXRz
  KAFKA-BROKER: a2Fma2E6OTA5Mg==
